"""empty message

Revision ID: e5746f001c61
Revises: 00e5b7fef2fe
Create Date: 2026-01-22 13:38:23.840971

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e5746f001c61"
down_revision: Union[str, None] = "00e5b7fef2fe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    shipmentstatus_enum = sa.Enum(
        "pending", "processing", "shipped", "in_transit", "delivered", "cancelled", "failed", name="shipmentstatus"
    )
    shipmentstatus_enum.create(op.get_bind(), checkfirst=True)
    op.execute("""
        ALTER TABLE shipment 
        ALTER COLUMN status 
        TYPE shipmentstatus 
        USING LOWER(status)::shipmentstatus
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        ALTER TABLE shipment 
        ALTER COLUMN status 
        TYPE VARCHAR(50) 
        USING status::text
    """)
    sa.Enum(name="shipmentstatus").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
