"""empty message

Revision ID: 00e5b7fef2fe
Revises: d0b0ca6bcc0a
Create Date: 2026-01-22 13:00:33.945820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00e5b7fef2fe'
down_revision: Union[str, None] = 'd0b0ca6bcc0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'shipment', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shipment', type_='unique')
    # ### end Alembic commands ###
