"""empty message

Revision ID: d0b0ca6bcc0a
Revises: 5622ebae5cca
Create Date: 2026-01-20 16:56:21.069490

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d0b0ca6bcc0a"
down_revision: Union[str, None] = "5622ebae5cca"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create enum type if it doesn't exist
    residentialindicator_enum = sa.Enum("UNKNOWN", "YES", "NO", name="residentialindicator")
    residentialindicator_enum.create(op.get_bind(), checkfirst=True)

    op.alter_column("address", "company_name", existing_type=sa.VARCHAR(length=255), nullable=True)
    op.alter_column("address", "address_line2", existing_type=sa.VARCHAR(length=255), nullable=True)
    op.alter_column("address", "address_line3", existing_type=sa.VARCHAR(length=255), nullable=True)
    # Convert VARCHAR to ENUM with USING clause
    # Convert string values to enum (handles both case variations)
    op.execute("""
        ALTER TABLE address 
        ALTER COLUMN address_residential_indicator 
        TYPE residentialindicator 
        USING UPPER(address_residential_indicator)::residentialindicator
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Convert ENUM back to VARCHAR
    op.execute("""
        ALTER TABLE address 
        ALTER COLUMN address_residential_indicator 
        TYPE VARCHAR(50) 
        USING address_residential_indicator::text
    """)
    op.alter_column("address", "address_line3", existing_type=sa.VARCHAR(length=255), nullable=False)
    op.alter_column("address", "address_line2", existing_type=sa.VARCHAR(length=255), nullable=False)
    op.alter_column("address", "company_name", existing_type=sa.VARCHAR(length=255), nullable=False)
    # Drop enum type
    sa.Enum(name="residentialindicator").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
